import React from "react";

export default function Privacy() {
  const supportEmail = "luxaarinstitute@gmail.com";

  return (
    <div className="mx-auto max-w-4xl space-y-8 px-5 py-14 text-ink">
      <h1 className="font-display text-4xl font-extrabold tracking-tight">Privacy Policy</h1>
      
      <div className="space-y-6 text-muted leading-relaxed">
        <p>
          This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your information when you use our Service, and tells you about your privacy rights and how the law protects you.
        </p>
        <p>
          We use your Personal Data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.
        </p>

        <h2 className="text-2xl font-bold text-ink mt-8">Interpretation and Definitions</h2>
        <p><strong>You</strong> means the individual accessing or using the Service.</p>
        <p><strong>Company</strong> (referred to as "the Company", "We", "Us", or "Our") refers to <strong>Luxaar Institute</strong>.</p>
        <p><strong>Service</strong> refers to the website and/or mobile application operated by Luxaar Institute.</p>
        <p><strong>Country</strong> refers to: Tamil Nadu, India.</p>
        <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
        <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</p>

        <h2 className="text-2xl font-bold text-ink mt-8">Collecting and Using Your Personal Data</h2>
        
        <h3 className="text-xl font-bold text-ink mt-6">Types of Data Collected</h3>
        <p><strong>Personal Data:</strong> While using our Service, we may ask you to provide certain personally identifiable information that can be used to contact or identify you, including but not limited to:</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Date of birth / educational details (where relevant for course enrollment)</li>
          <li>Payment and transaction details (billing name, order ID, transaction ID) — card, UPI, and net-banking credentials are handled directly by our payment gateway partner (PhonePe) and are never stored on our servers.</li>
        </ul>

        <p><strong>Usage Data:</strong> Usage Data is collected automatically when using the Service, and may include your device's IP address, browser type and version, the pages of our Service that you visit, time and date of visit, time spent on those pages, unique device identifiers, course progress, and test/quiz performance data.</p>

        <h3 className="text-xl font-bold text-ink mt-6">Tracking Technologies and Cookies</h3>
        <p>We use cookies and similar tracking technologies to track activity on our Service and store certain information, including to keep you logged in, remember preferences, and analyze usage of the Service. You can instruct your browser to refuse cookies; however, some features of the Service may not function properly without them.</p>

        <h3 className="text-xl font-bold text-ink mt-6">Use of Your Personal Data</h3>
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>To provide and maintain our Service, including course access and progress tracking</li>
          <li>To manage your Account and course enrollments</li>
          <li>For the performance of a contract: processing your course purchase and delivering the purchased content</li>
          <li>To contact you by email, phone, SMS, or push notification regarding class schedules, updates, or support requests</li>
          <li>To send you information about new courses, offers, and exam updates, unless you opt out</li>
          <li>To manage and respond to your requests and support queries</li>
          <li>To detect, prevent, and address fraud, unauthorized access, or misuse of course content</li>
        </ul>

        <h3 className="text-xl font-bold text-ink mt-6">Sharing of Your Personal Data</h3>
        <p>We may share your personal information in the following situations:</p>
        <ul className="list-disc pl-6 space-y-1">
          <li><strong>With Service Providers</strong>, including our payment gateway partner (PhonePe), cloud hosting, SMS/email providers, and analytics tools, solely to operate the Service</li>
          <li><strong>For Business Transfers</strong>, in connection with a merger, acquisition, or sale of Company assets</li>
          <li><strong>With Faculty/Educators</strong>, limited to information needed for academic mentoring and doubt resolution</li>
          <li><strong>With Law Enforcement</strong>, where required to comply with a legal obligation or valid request by public authorities</li>
        </ul>
        <p>We do not sell your personal information to third parties.</p>

        <h3 className="text-xl font-bold text-ink mt-6">Retention of Your Personal Data</h3>
        <p>The Company will retain your Personal Data only for as long as necessary for the purposes set out in this Privacy Policy, including to comply with legal obligations, resolve disputes, and enforce our agreements.</p>

        <h3 className="text-xl font-bold text-ink mt-6">Security of Your Personal Data</h3>
        <p>The security of your Personal Data is important to us, but no method of transmission over the internet or electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

        <h3 className="text-xl font-bold text-ink mt-6">Children's Privacy</h3>
        <p>Our Service is intended for users generally aged 13 and above. We do not knowingly collect personally identifiable information from anyone under the age of 13 without parental consent. If you are a parent or guardian and believe your child has provided us with Personal Data, please contact us so we can take appropriate action.</p>

        <h3 className="text-xl font-bold text-ink mt-6">Links to Other Websites</h3>
        <p>Our Service may contain links to other websites not operated by us, including official exam authority websites. We strongly advise you to review the Privacy Policy of every site you visit, as we have no control over and assume no responsibility for third-party content or practices.</p>

        <h3 className="text-xl font-bold text-ink mt-6">Changes to This Privacy Policy</h3>
        <p>We may update this Privacy Policy from time to time. We will notify you of changes by posting the new Privacy Policy on this page and updating the "Last updated" date. You are advised to review this Privacy Policy periodically.</p>

        <hr className="my-8 border-gray-200" />
        
        <p>If you have any questions about this Privacy Policy, you can contact us at <strong>{supportEmail}</strong>.</p>
      </div>
    </div>
  );
}
